server:
  port: 8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    instance-id: eureka-server-service

spring:
  application:
    name: eureka
