server:
  port: 8080

spring:
  application:
    name: zuulGateway

zuul:
  ribbon:
    eager-load:
      enabled: true
  sensitive-headers:
  routes:
    sendMessage:
#      path: /sendmessage/**
      serviceId: send-message
#      stripPrefix: true
    toAcceptMessage:
      path: /acceptmessage/**
      serviceId: to-accept-message
      stripPrefix: true
