server:
  port: 8080

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: zuul-gateway-service

zuul:
  ribbon:
    eager-load:
      enabled: true
  sensitive-headers:

  routes:
   sendMessage:
      path: /send/**
      serviceId: send-message
      stripPrefix: true

    toAcceptMessage:
      path: /accept/**
      serviceId: to-accept-message
      stripPrefix: true
