server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: zuul-server

spring:
  application:
    name: zuul-server

zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    send-message:
      path: /send/**
      serviceId: send-message
      stripPrefix: true
    to-accept-message:
      path: /accept/**
      serviceId: to-accept-message
      stripPrefix: true



