server:
  port: 8080

spring:
  application:
    name: zuulGateway

zuul:
  routes:
    sendMessage-service:
      path: /sendMessage-service/**
      serviceId: sendMessage
#      url:
#      stripPrefix: true

##    name1:
#      path:
#      serviceId:
#      stripPrefix:
