server:
  port: 8082

spring:
  profiles:
    default: dev
  application:
    name: accept-message
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 821252
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: accept-message-service

