server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: accept-message-service

spring:
  application:
    name: accept-message
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 821252

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

