server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: send-message-service
spring:
  application:
    name: send-message
